services:
  app:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    hostname: getha
    container_name: getha-backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - aparelhosData:/app/aparelhos
      - zoonoseData:/app/zoonose
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=enzofernandes123
      - POSTGRES_DB=gethadb
    privileged: true

  db:
    network_mode: host
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=enzofernandes123
      - POSTGRES_DB=gethadb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gethadb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  aparelhosData:
  zoonoseData: